// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReactionVideoAggregator.Data;
using ReactionVideoAggregator.Models;

#nullable disable

namespace ReactionVideoAggregator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260813004222_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReactionVideoAggregator.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TmdbId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("ReactionVideoAggregator.Models.ReactionVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<ExternalLinks>("ExternalLinks")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReactorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YouTubeUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("ReactorId");

                    b.ToTable("ReactionVideos");
                });

            modelBuilder.Entity("ReactionVideoAggregator.Models.Reactor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<PatreonData>("PatreonData")
                        .HasColumnType("jsonb");

                    b.Property<string>("YouTubeChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Reactors");
                });

            modelBuilder.Entity("ReactionVideoAggregator.Models.ReactionVideo", b =>
                {
                    b.HasOne("ReactionVideoAggregator.Models.Movie", "Movie")
                        .WithMany("ReactionVideos")
                        .HasForeignKey("MovieId");

                    b.HasOne("ReactionVideoAggregator.Models.Reactor", "Reactor")
                        .WithMany("ReactionVideos")
                        .HasForeignKey("ReactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Reactor");
                });

            modelBuilder.Entity("ReactionVideoAggregator.Models.Movie", b =>
                {
                    b.Navigation("ReactionVideos");
                });

            modelBuilder.Entity("ReactionVideoAggregator.Models.Reactor", b =>
                {
                    b.Navigation("ReactionVideos");
                });
#pragma warning restore 612, 618
        }
    }
}
